replicaCount: 1

image:
  repository: sshivaji555/mlops-app
  tag: 'v1.0.1'
  pullPolicy: Always

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 30800

# Fixed YAML list format for K8s environment variables
env:
  - name: MLFLOW_TRACKING_URI
    value: "http://192.168.235.130:5000"
  - name: AWS_ACCESS_KEY_ID
    value: "minioadmin"
  - name: AWS_SECRET_ACCESS_KEY
    value: "minioadmin"
  - name: MLFLOW_S3_ENDPOINT_URL
    value: "http://192.168.235.130:9000"
  - name: GIT_PYTHON_REFRESH
    value: "quiet"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi